---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: libnetwork
  namespace: kube-system

---

apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: libnetwork
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: libnetwork
subjects:
- kind: ServiceAccount
  name: libnetwork
  namespace: kube-system
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: libnetwork
  namespace: kube-system
rules:
  - apiGroups:
    - ""
    - extensions
    resources:
      - pods
      - nodes
      - namespaces
    verbs:
      - get
      - list
      - update
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: dnet-config
  namespace: kube-system
data:
  cluster_store: "etcd://10.96.0.2:12389"
  cni_config: |-
    {
      "cniVersion": "0.2.0",
      "name": "dnet-bridge",
      "type": "dnet-cni",
      "ipam": {
              "preferred-pool": "10.22.0.0/16"
      }
    }

---

kind: DaemonSet
apiVersion: extensions/v1beta1
metadata:
  name: libnetwork
  namespace: kube-system
  labels:
    k8s-app: libnetwork
spec:
  selector:
    matchLabels:
      k8s-app: libnetwork
  template:
    metadata:
      labels:
        k8s-app: libnetwork
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ''
        scheduler.alpha.kubernetes.io/tolerations: |
          [{"key":"CriticalAddonsOnly", "operator":"Exists"}]
    spec:
      hostNetwork: true
      hostPID: true
      serviceAccountName: libnetwork
      containers:
        - name: libnetwork-dnet
          image: abhinandan03/dnet:0.1.0
          env:
            - name: DNET_ADDRESS
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: DNET_DISCOVERY
              valueFrom:
                configMapKeyRef:
                  name: dnet-config
                  key: cluster_store
          securityContext:
            privileged: true
          volumeMounts:
            - mountPath: /home/libnetwork/
              name: var-libnetwork
              readOnly: false
            - mountPath: /var/run
              name: var-run
              readOnly: false
            - name: run
              mountPath: /run/netns/

        - name: libnetwork-cniserver
          image: abhinandan03/cniserver:0.1.0
          env:
            - name: DNET_ADDRESS
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: DNET_CNI_CONF
              valueFrom:
                configMapKeyRef:
                  name: dnet-config
                  key: cni_config
          securityContext:
            privileged: true

          volumeMounts:
            - mountPath: /opt/cni/bin
              name: cni-bin-dir
              readOnly: false
            - mountPath: /etc/cni/net.d/
              name: etc-cni-dir
              readOnly: false
            - mountPath: /home/libnetwork/
              name: var-libnetwork
              readOnly: false
            - mountPath: /var/run
              name: var-run
              readOnly: false

      volumes:
        - name: cni-bin-dir
          hostPath:
            path: /opt/cni/bin
        - name: etc-cni-dir
          hostPath:
            path: /etc/cni/net.d/
        - name: var-libnetwork
          hostPath:
            path: /var/libnetwork/
        - name: var-run
          hostPath:
            path: /var/run
        - name: run
          hostPath:
            path: /run/netns

---
